export default {
  FETCH_COMPANIES_REQUEST: 'FETCH_COMPANIES_REQUEST',
  FETCH_COMPANIES_SUCCESS: 'FETCH_COMPANIES_SUCCESS',
  FETCH_COMPANIES_FAILURE: 'FETCH_COMPANIES_FAILURE',
  UPDATE_CURRENT_PAGE: 'UPDATE_CURRENT_PAGE',
  RESET_COMPANIES: 'RESET_COMPANIES',
  UPDATE_COMPANIES_SEARCH: 'UPDATE_COMPANIES_SEARCH'
}
