export default {
  SAVE_COMPANY_REQUEST: 'SAVE_COMPANY_REQUEST',
  SAVE_COMPANY_SUCCESS: 'SAVE_COMPANY_SUCCESS',
  SAVE_COMPANY_FAILURE: 'SAVE_COMPANY_FAILURE',
  FETCH_COMPANY_REQUEST: 'FETCH_COMPANY_REQUEST',
  FETCH_COMPANY_SUCCESS: 'FETCH_COMPANY_SUCCESS',
  FETCH_COMPANY_FAILURE: 'FETCH_COMPANY_FAILURE',
  UPDATE_COMPANY: 'UPDATE_COMPANY',
  RESET_COMPANY: 'RESET_COMPANY'
}
