export default {
  SAVE_JOB_REQUEST: 'SAVE_JOB_REQUEST',
  SAVE_JOB_SUCCESS: 'SAVE_JOB_SUCCESS',
  SAVE_JOB_FAILURE: 'SAVE_JOB_FAILURE',
  FETCH_JOB_REQUEST: 'FETCH_JOB_REQUEST',
  FETCH_JOB_SUCCESS: 'FETCH_JOB_SUCCESS',
  FETCH_JOB_FAILURE: 'FETCH_JOB_FAILURE',
  UPDATE_JOB: 'UPDATE_JOB',
  RESET_JOB: 'RESET_JOB'
}
