export default {
  FETCH_JOBS_REQUEST: 'FETCH_JOBS_REQUEST',
  FETCH_JOBS_SUCCESS: 'FETCH_JOBS_SUCCESS',
  FETCH_JOBS_FAILURE: 'FETCH_JOBS_FAILURE',
  UPDATE_CURRENT_PAGE: 'UPDATE_CURRENT_PAGE',
  RESET_JOBS: 'RESET_JOBS',
  UPDATE_JOBS_SEARCH: 'UPDATE_JOBS_SEARCH'
}
