export default {
  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  UPDATE_CURRENT_PAGE: 'UPDATE_CURRENT_PAGE',
  RESET_USERS: 'RESET_USERS',
  UPDATE_USERS_SEARCH: 'UPDATE_USERS_SEARCH'
}
